[package]
name = "minxent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipopt = "0.5.4"
rand = "0.8.5"
nalgebra = "0.31.1"
num-traits = "0.2.15"
